name: unit-tests
on: [push, pull_request]
jobs:
  unit_test:
    name: unit_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        vim:
          - nightly
          - v9.1.2125
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2

      - name: Precompile Julia packages
        run: |
          julia -e 'using DataFrames, PrettyTables'

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.12'

      - name: Install python packages
        run: |
          pip install ipython
          pip install numpy
          pip install pandas

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}

      - name: Checkout vim-replica plugin code
        uses: actions/checkout@v6

      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          source ./run_tests.sh 1


  unit_test_windows:
    name: unit_test_windows
    runs-on: windows-latest
    strategy:
      matrix:
        vim:
          - nightly
          - v9.1.2125

    steps:
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2

      - name: Precompile Julia packages
        run: |
          julia -e 'using DataFrames, PrettyTables'

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.12'

      - name: Install python packages
        run: |
          pip install ipython
          pip install numpy
          pip install pandas

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}

      - name: Checkout vim-replica plugin code
        uses: actions/checkout@v6

      - name: Run Tests
        run: |
          systeminfo
          echo "Vim command setup."
          $Env:VIMPRG = "${{ steps.vim.outputs.executable }}"
          & $Env:VIMPRG --version
          cd test
          .\run_tests.cmd
